# Generated by Django 5.0.6 on 2024-06-20 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_info'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderForm',
            new_name='CustomerInfo',
        ),
    ]
