# Generated by Django 5.0.6 on 2024-06-20 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_rename_orderform_customerinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='info',
            new_name='customer_info',
        ),
    ]
