# Generated by Django 5.0.6 on 2024-06-21 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_order_cart_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='mobile',
            field=models.IntegerField(max_length=13),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='order.order'),
        ),
    ]
