# Generated by Django 5.0.6 on 2024-06-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_customerinfo_mobile_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
