# Generated by Django 5.0.6 on 2024-06-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_customerinfo_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='mobile',
            field=models.TextField(),
        ),
    ]
