# Generated by Django 5.0.6 on 2024-06-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='default/default-product-image.png', null=True, upload_to='products_pictures/'),
        ),
    ]
